name: Docker Variation Tests - PHP (Build-Push Action)

on:
  workflow_dispatch:

jobs:
  build_php_buildpush_action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variation: "02-phpfpm-nginx"
            complexity: "MEDIUM"
          - variation: "05-non-root-user"
            complexity: "MEDIUM"
          - variation: "07-healthcheck"
            complexity: "MEDIUM"
          - variation: "08-buildkit-composer-cache"
            complexity: "MEDIUM-HIGH"
          - variation: "15-full-production-grade"
            complexity: "HIGHEST"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: "PHP | Dockerfile.${{ matrix.variation }} [complexity=${{ matrix.complexity }}]"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-test-variations/php/Dockerfile.${{ matrix.variation }}
          push: false
          load: true
          tags: php-action-${{ matrix.variation }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
